chore(ci): Create rpm packages
We now create RPM packages for the following Linux distributions:

- Fedora 36
- OpenSUSE Leap 15

The rationale for choosing those specific versions is simple: They're
the oldest, yet still supported releases.

We also tell CMake to build a position independent executable (PIE) [1]
to get rid of this warning given by rpmlint:

notes.x86_64: W: position-independent-executable-suggested /usr/bin/notes

Likewise with the DEB package, there's also some other warnings related
to missing documentation, but those can be addressed in the future.

[1] https://cmake.org/cmake/help/latest/prop_tgt/POSITION_INDEPENDENT_CODE.html

diff --git a/.github/workflows/linux.yml b/.github/workflows/linux.yml
--- a/.github/workflows/linux.yml
+++ b/.github/workflows/linux.yml
@@ -72,7 +72,7 @@ jobs:
               echo 'Fatal: Failed to extract distro ID from /etc/os-release'
               exit 1
           fi
-          distro_codename=$(grep -oPm1 '^VERSION_CODENAME="?\K[^"]+$' /etc/os-release)
+          distro_codename=$(grep -oPm1 '^VERSION_CODENAME="?\K[^"]+' /etc/os-release)
           if [ -z "${distro_codename}" ]
           then
               echo 'Fatal: Failed to extract distro codename from /etc/os-release'
@@ -135,6 +135,112 @@ jobs:
           if-no-files-found: error
           name: ${{ steps.deb.outputs.name }}-qt${{ matrix.qt-version-major }}-${{ steps.vars.outputs.distro_name }}-${{ matrix.build-type }}
           path: ${{ steps.deb.outputs.path }}
+
+  rpm:
+    name: rpm (${{ matrix.build-type }}, Qt ${{ matrix.qt-version-major }}, ${{ matrix.container != '' && matrix.container || matrix.os }})
+    runs-on: ${{ matrix.os }}
+    container: ${{ matrix.container }}
+    strategy:
+      fail-fast: false
+      matrix:
+        include:
+          - os: ubuntu-20.04
+            container: fedora:36
+            qt-version-major: 6
+            build-type: release
+
+          - os: ubuntu-20.04
+            container: opensuse/leap:15
+            qt-version-major: 6
+            build-type: release
+    steps:
+      - name: Install build dependencies
+        env:
+          PKG_MANAGER: ${{ startsWith(matrix.container, 'fedora') && 'dnf' || 'zypper' }}
+          # Fedora doesn't include libxkbcommon-devel as a dependency of Qt 6, so have to install it manually.
+          PKG_LIST: ${{ startsWith(matrix.container, 'fedora') && 'libxkbcommon-devel qt6-qtbase-private-devel' || 'qt6-base-private-devel' }}
+        run: |
+          ${{ env.PKG_MANAGER }} update -y
+          ${{ env.PKG_MANAGER }} install -y cmake gcc git ${{ env.PKG_LIST }} rpm-build rpmlint
+          # Prevent git's dubious ownership message
+          git config --global --add safe.directory "${PWD}"
+
+      - name: Checkout code
+        uses: actions/checkout@v3
+        with:
+          submodules: recursive
+
+      - name: Set up variables
+        shell: bash
+        id: vars
+        run: |
+          set -x
+          distro_id=$(grep -oPm1 '^ID="?\K[^"]+' /etc/os-release)
+          if [ -z "${distro_id}" ]
+          then
+              echo 'Failed to extract distro ID from /etc/os-release.'
+              exit 1
+          fi
+          version_id=$(grep -oPm1 '^VERSION_ID="?\K[^"]+' /etc/os-release)
+          if [ -z "${version_id}" ]
+          then
+              echo 'Failed to extract version id from /etc/os-release.'
+              exit 1
+          fi
+          echo "distro_name=${distro_id}-${version_id}" >> "${GITHUB_OUTPUT}"
+
+      - name: Setup GCC problem matcher
+        uses: ammaraskar/gcc-problem-matcher@0.2.0
+
+      - name: Build (${{ matrix.build-type }})
+        env:
+          VERBOSE: 1
+          # openSUSE defaults to GCC 7, which doesn't support the filesystem library from C++17,
+          # and causes trouble compiling for Qt 6. So we have to manully specify GCC 10 instead.
+          CXX: ${{ startsWith(matrix.container, 'opensuse') && 'g++-10' || 'g++' }}
+        run: |
+          cmake --warn-uninitialized --warn-unused-vars \
+              -B build \
+              -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} \
+              -DGIT_REVISION=${{ github.ref_type != 'tag' && 'ON' || 'OFF' }} \
+              -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE \
+              -DUPDATE_CHECKER=OFF \
+              -DUSE_QT_VERSION=${{ matrix.qt-version-major }}
+          cmake --build build --parallel $(nproc)
+
+      - name: Strip debug symbols (release-only)
+        if: matrix.build-type == 'release'
+        run: |
+          strip -s build/notes
+
+      - name: Create rpm package
+        run: |
+          cd build
+          cpack -G RPM
+
+      - name: Grab rpm package name
+        id: rpm
+        shell: bash
+        run: |
+          set -x
+          if ! path=$(find build/ -maxdepth 1 -name '*.rpm' -print -quit)
+          then
+              echo 'Fatal: Unable to find rpm package!'
+              exit 1;
+          fi
+          echo "name=$(basename "${path%.*}")" >> "${GITHUB_OUTPUT}"
+          echo "path=${path}" >> "${GITHUB_OUTPUT}"
+
+      - name: Run rpmlint
+        run: |
+          rpmlint '${{ steps.rpm.outputs.path }}'
+
+      - name: Upload rpm package
+        uses: actions/upload-artifact@v3
+        with:
+          if-no-files-found: error
+          name: ${{ steps.rpm.outputs.name }}-qt${{ matrix.qt-version-major }}-${{ steps.vars.outputs.distro_name }}-${{ matrix.build-type }}
+          path: ${{ steps.rpm.outputs.path }}
 
   # Build the AppImage using official Qt releases, downloaded by aqtinstall.
   # This is also done for macOS and Windows, just to make sure we use the exact same Qt version across all three OSes.
