chore(ci): Create deb packages
Right now, we create deb packages for the following Ubuntu releases:

- 18.04 Bionic Beaver (oldest supported LTS)
- 20.04 Focal Fossa (newest supported LTS)
- 22.10 Kinetic Kudu (latest, non-LTS release)

diff --git a/.github/workflows/linux.yml b/.github/workflows/linux.yml
--- a/.github/workflows/linux.yml
+++ b/.github/workflows/linux.yml
@@ -11,11 +11,8 @@ env:
   APP_ID: io.github.nuttyartist.notes
 
 jobs:
-  # This job is mainly to make sure Notes will compile with Qt from Ubuntu's repository.
-  # So it doesn't make much sense to have different build types other than 'debug' here.
-  # The release AppImage is built using aqtinstall instead (the job below this one).
-  build-apt:
-    name: Build (${{ matrix.build-type }}, apt (qt${{ matrix.qt-version-major }}), ${{ matrix.container != '' && matrix.container || matrix.os }})
+  deb:
+    name: deb (${{ matrix.build-type }}, Qt ${{ matrix.qt-version-major }}, ${{ matrix.container != '' && matrix.container || matrix.os }})
     runs-on: ${{ matrix.os }}
     container: ${{ matrix.container }}
     strategy:
@@ -25,18 +22,18 @@ jobs:
           - os: ubuntu-20.04
             # TODO: Replace 'ubuntu:18.04' by 'ubuntu:20.04' when:
             # - Ubuntu 18.04 officially reaches EOL (scheduled to April, 2023 - https://wiki.ubuntu.com/Releases)
-            # - A new build of linuxdeployqt allows us to build on Ubuntu 20.04, without having to use -unsupported-allow-new-glibc.
             container: ubuntu:18.04
             qt-version-major: 5
-            build-type: debug
-
-          - os: ubuntu-latest
-            qt-version-major: 5
-            build-type: debug
+            build-type: release
 
           - os: ubuntu-22.04
             qt-version-major: 6
-            build-type: debug
+            build-type: release
+
+          - os: ubuntu-20.04
+            container: ubuntu:22.10
+            qt-version-major: 6
+            build-type: release
     steps:
       - name: Install git PPA in docker container
         # A more recent version of git is required by the checkout action: https://github.com/actions/checkout/issues/758
@@ -56,21 +53,39 @@ jobs:
         run: |
           apt update
           apt install -y git sudo
+          # Prevent git's dubious ownership message
+          git config --global --add safe.directory "${PWD}"
 
       - name: Checkout code
         uses: actions/checkout@v3
         with:
           submodules: recursive
 
-      - name: Install Qt ${{ matrix.qt-version-major }} (apt)
-        env:
-          QT_PKGS: ${{ matrix.qt-version-major == '6' && 'qt6-base-private-dev libgl-dev' || 'qtbase5-private-dev' }}
+      - name: Set up variables
+        shell: bash
+        id: vars
+        run: |
+          set -x
+          distro_id=$(grep -oPm1 '^ID="?\K[^"]+' /etc/os-release)
+          if [ -z "${distro_id}" ]
+          then
+              echo 'Fatal: Failed to extract distro ID from /etc/os-release'
+              exit 1
+          fi
+          distro_codename=$(grep -oPm1 '^VERSION_CODENAME="?\K[^"]+$' /etc/os-release)
+          if [ -z "${distro_codename}" ]
+          then
+              echo 'Fatal: Failed to extract distro codename from /etc/os-release'
+              exit 1
+          fi
+          echo "distro_name=${distro_id}-${distro_codename}" >> "${GITHUB_OUTPUT}"
+
+      - name: Install build dependencies
         run: |
           sudo apt update
-          sudo apt install -y build-essential cmake ${{ env.QT_PKGS }}
+          sudo apt install -y build-essential cmake lintian ${{ matrix.qt-version-major == '6' && 'qt6-base-private-dev libgl-dev' || 'qtbase5-private-dev' }}
 
       - name: Setup GCC problem matcher
-        if: matrix.build-type == 'debug'
         uses: ammaraskar/gcc-problem-matcher@0.2.0
 
       # TODO: Migrate to the Ninja generator once we drop support for Ubuntu 18.04.
@@ -80,8 +95,46 @@ jobs:
         run: |
           mkdir build
           cd build
-          cmake .. --warn-uninitialized --warn-unused-vars -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}
+          cmake .. --warn-uninitialized --warn-unused-vars \
+              -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} \
+              -DGIT_REVISION=${{ github.ref_type != 'tag' && 'ON' || 'OFF' }} \
+              -DUPDATE_CHECKER=OFF \
+              -DUSE_QT_VERSION=${{ matrix.qt-version-major }}
           make -j$(nproc)
+
+      - name: Strip debug symbols (release-only)
+        if: matrix.build-type == 'release'
+        run: |
+          strip -s build/notes
+
+      - name: Create deb package
+        run: |
+          cd build
+          cpack -G DEB
+
+      - name: Grab deb package name
+        id: deb
+        shell: bash
+        run: |
+          set -x
+          if ! path=$(find build/ -maxdepth 1 -name '*.deb' -print -quit)
+          then
+              echo 'Fatal: Unable to find deb package'
+              exit 1;
+          fi
+          echo "name=$(basename "${path%.*}")" >> "${GITHUB_OUTPUT}"
+          echo "path=${path}" >> "${GITHUB_OUTPUT}"
+
+      - name: Run lintian
+        run: |
+          lintian '${{ steps.deb.outputs.path }}'
+
+      - name: Upload deb package
+        uses: actions/upload-artifact@v3
+        with:
+          if-no-files-found: error
+          name: ${{ steps.deb.outputs.name }}-qt${{ matrix.qt-version-major }}-${{ steps.vars.outputs.distro_name }}-${{ matrix.build-type }}
+          path: ${{ steps.deb.outputs.path }}
 
   # Build the AppImage using official Qt releases, downloaded by aqtinstall.
   # This is also done for macOS and Windows, just to make sure we use the exact same Qt version across all three OSes.
