fix(build): Forward app version to CMake's project()
This fixes an incorrect version string being set in the app.

Unfortunately, the side effect is that project() seems to be very
strict about what string we can use as a version, so we have to remove
the "Update version" step on the CI pipeline, in order to prevent CMake
from barking at us...

And then finally, we replace $CMAKE_PROJECT_VERSION by $PROJECT_VERSION,
because the former is only available on CMake 3.12+.

diff --git a/.github/workflows/macos.yml b/.github/workflows/macos.yml
--- a/.github/workflows/macos.yml
+++ b/.github/workflows/macos.yml
@@ -78,19 +78,27 @@ jobs:
         with:
           submodules: recursive
 
-      - name: Update version
-        run: |
-          sed -i.bak "s/[^_]PROJECT_VERSION *[^)]\+/&-g${GITHUB_SHA::7}/" CMakeLists.txt
-
       - name: Setup variables
         id: vars
         run: |
-          version=$(grep -m 1 '[^_]PROJECT_VERSION' CMakeLists.txt | sed 's/.*[^_]PROJECT_VERSION *//' | sed 's/).*//')
+          set -x
+          version=$(grep -Em1 '\bAPP_VERSION' CMakeLists.txt | sed -r 's/.*APP_VERSION +//; s/ *)//')
+          if [ -z "${version}" ]
+          then
+              echo 'Failed to extract app version from CMakeLists.txt.'
+              exit 1
+          fi
+          version="${version}-g${GITHUB_SHA::7}"
           artifact_name="Notes_${version}-x86_64-Qt${{ matrix.qt-version }}"
-          file_name="$artifact_name${{ matrix.build-type == 'debug' && '-debug.' || '.' }}dmg"
-          echo "version=$version" >> $GITHUB_OUTPUT
-          echo "artifact_name=$artifact_name" >> $GITHUB_OUTPUT
-          echo "file_name=$file_name" >> $GITHUB_OUTPUT
+          if [ '${{ matrix.build-type }}' == 'debug' ]
+          then
+              file_name="${artifact_name}-debug.dmg"
+          else
+              file_name="${artifact_name}.dmg"
+          fi
+          echo "version=${version}" >> "${GITHUB_OUTPUT}"
+          echo "artifact_name=${artifact_name}" >> "${GITHUB_OUTPUT}"
+          echo "file_name=${file_name}" >> "${GITHUB_OUTPUT}"
 
       - name: Install Qt ${{ matrix.qt-version }} (aqtinstall)
         uses: jurplel/install-qt-action@v3
